[simulation]
timestep_s = 1.0

[chamber]
radius_m = 3
length_m = 9

[[geometry]]
name = "Emitter"
file = "o_rect.obj"
emit = true
collect = false
scale = { x = 0.25, y = 0.25, z = 0.25 }
translate = { x = 0.0, y = 0.125, z = -3.0 }
color = { x = 0.5, y = 0.0, z = 0.5 }

[geometry.emitter]
flux = 10

[[geometry]]
name = "Collector"
file = "o_sphere.obj"
emit = false
collect = true
translate = { x = 0.0, y = 0.0, z = 3.0 }
color = { x = 0.0, y = 0.5, z = 0.0 }

[[particle]]
position = { x = 0, y = 0.0, z = -2.0 }
velocity = { x = 0.0, y = 0.0, z = 1.0 }
weight = 1
