[[particle]]
position = {x = 0, y = 0, z = 0}
velocity = {x = 0, y = 0, z = 0}
weight = 1

[chamber]
radius = 3
length = 9

[[geometry]]
name = "beam dump"
file = "o_beamdump.obj"
emit = true
collect = false
scale = {x = 5.0, y = 1.0, z = 1.0}

[[geometry]]
name = "cube"
file = "o_cube.obj"
emit = true
collect = false
translate = {x = 3, y = 3, z = 3}

[[geometry]]
name = "sphere"
file = "o_sphere.obj"
emit = true
collect = false
scale = {x = 1.0, y = 0.5, z = 0.5}

[[geometry]]
name = "Collector"
file = "o_collector.obj"
emit = false
collect = true
scale = {x = 1.0, y = 5.0, z = 1.0}
translate = {x = 0.0, y = 0.0, z = 2.0}
