[simulation]
timestep_s = 0.005
max_time_s = 0.1
output_interval_s = 0.01

[chamber]
radius_m = 3
length_m = 6

[[material]]
name = "carbon"
color = { x = 0.3, y = 0.3, z = 0.3 }
sticking_coeff = 0.2
diffuse_coeff = 0.8
temperature_K = 300

[[geometry]]
name = "Emitter"
file = "o_rect.obj"
material = "carbon"
emit = true
scale = { x = 0.25, y = 0.25, z = 0.25 }
translate = { x = 0.0, y = 0.125, z = -2.0 }
color = { x = 0.2, y = 0.2, z = 0.8 }

[geometry.emitter]
flux = 5_000_000
velocity = 300
spread = 0.1
reverse_direction = false

#[[geometry]]
#name = "Reflector (flat)"
#file = "o_rect.obj"
#material = "carbon"
#translate = { x = 0.0, y = 0.0, z = 2.0 }
#scale = { x = 2.0, y = 2.0, z = 2.0 }
#color = { x = 0.8, y = 0.8, z = 0.8 }

[[geometry]]
name = "Reflector l2"
file = "o_rect.obj"
material = "carbon"
scale = { x = 0.25, y = 1.0, z = 1.0 }
translate = { x = 1.25, y = 0.0, z = 2.0 }
rotate = { axis = { x = 0.0, y = 1.0, z = 0.0 }, angle = -15 }

[[geometry]]
name = "Reflector l1"
file = "o_rect.obj"
material = "carbon"
scale = { x = 0.25, y = 1.0, z = 1.0 }
translate = { x = 0.75, y = 0.0, z = 2.0 }
rotate = { axis = { x = 0.0, y = 1.0, z = 0.0 }, angle = -15 }

[[geometry]]
name = "Reflector l0"
file = "o_rect.obj"
material = "carbon"
scale = { x = 0.25, y = 1.0, z = 1.0 }
translate = { x = 0.25, y = 0.0, z = 2.0 }
rotate = { axis = { x = 0.0, y = 1.0, z = 0.0 }, angle = -15 }

[[geometry]]
name = "Reflector r0"
file = "o_rect.obj"
material = "carbon"
scale = { x = 0.25, y = 1.0, z = 1.0 }
translate = { x = -0.25, y = 0.0, z = 2.0 }
rotate = { axis = { x = 0.0, y = 1.0, z = 0.0 }, angle = 15 }

[[geometry]]
name = "Reflector r1"
file = "o_rect.obj"
material = "carbon"
scale = { x = 0.25, y = 1.0, z = 1.0 }
translate = { x = -0.75, y = 0.0, z = 2.0 }
rotate = { axis = { x = 0.0, y = 1.0, z = 0.0 }, angle = 15 }

[[geometry]]
name = "Reflector r2"
file = "o_rect.obj"
material = "carbon"
scale = { x = 0.25, y = 1.0, z = 1.0 }
translate = { x = -1.25, y = 0.0, z = 2.0 }
rotate = { axis = { x = 0.0, y = 1.0, z = 0.0 }, angle = 15 }

[[geometry]]
name = "Collector"
file = "o_rect.obj"
material = "carbon"
collect = true
scale = { x = 0.15, y = 0.15, z = 0.15 }
color = { x = 0.9, y = 0.1, z = 0.1 }
translate = { x = 1.5, y = 0.0, z = 0.0 }
rotate = { angle = -45 }
