[simulaton]
timestep_s = 0.01

[chamber]
radius_m = 3
length_m = 9

[[geometry]]
name = "Collector"
file = "o_collector.obj"
emit = false
collect = true
translate = { x = 0.0, y = 0.0, z = 1.0 }
color = { x = 0.5, y = 0.5, z = 0.0 }

[[particle]]
position = { x = 0, y = 0, z = 0 }
velocity = { x = 0, y = 0, z = 0 }
weight = 1

[[particle]]
position = { x = 0, y = 0.5, z = -3.0 }
velocity = { x = 0.0, y = 0.0, z = 1.0 }
weight = 1
